PRESET_PARAMS = {
    "lite": {
        # Faster exploration within tight budget
        "n_generations": 12, 
        "n_parents": 15,
        "n_children": 90,  
        "early_stopping_child_eval": 25,  
        "early_stopping_iter": 5,  
        "min_pct_gain": 0.003, 
        "max_gen_new_feats_pct": 0.6, 
        "time_budget": 5 * 60, # 5 minutes
        "cv": 4,
        "ranking_method": "multi_criteria",
        "search_sample_size": 10_000,
        "cache_size_mb": 500,
        "use_proxy_evaluation": True,
        "proxy_top_pct": 0.20,
        "meta_validation_frac": 0.15,
        "rotate_cv_folds": True,
        "fold_rotation_period": 4,
        # --- search upgrades ---
        "prefilter_candidates": True,
        "near_dup_threshold": 0.99,
        "proxy_fast_mode": True,
        "proxy_num_rounds": 30,
        "proxy_pipeline_candidates": True,
        "elite_ranking": "proxy_blend",
        "cache_baseline_evals": True,
        "importance_refresh_period": 3,
        "shap_refresh_period": 5,
        "shap_interactions_max_pairs": 2000,
        "deadline_reserve_frac": 0.12,
        "fold_consistency_gate": True,
        "fold_consistency_min_frac": 0.65,
        "noise_probes": 5,
        "noise_probe_quantile": 0.5,
        "meta_gate": True,
        "meta_gate_epsilon": -0.02,
        "use_op_priors": True,
        "warm_start_battery": True,
        "warm_start_top_k": 6,
        "proxy_max_rows": 4000,
    },
    "medium": {
        # Better exploration/exploitation balance
        "n_generations": 25,
        "n_parents": 25,
        "n_children": 150,
        "early_stopping_child_eval": 35,
        "early_stopping_iter": 6,
        "min_pct_gain": 0.002,
        "max_gen_new_feats_pct": 1.2,
        "time_budget": 15 * 60, # 15 minutes
        "cv": 4,
        "ranking_method": "multi_criteria",
        "search_sample_size": 10_000,
        "cache_size_mb": 1000,
        "use_proxy_evaluation": True,
        "proxy_top_pct": 0.15,
        "meta_validation_frac": 0.15,
        "rotate_cv_folds": True,
        "fold_rotation_period": 5,
        # --- search upgrades ---
        "prefilter_candidates": True,
        "near_dup_threshold": 0.99,
        "proxy_fast_mode": True,
        "proxy_num_rounds": 30,
        "proxy_pipeline_candidates": True,
        "elite_ranking": "proxy_blend",
        "cache_baseline_evals": True,
        "importance_refresh_period": 3,
        "shap_refresh_period": 5,
        "shap_interactions_max_pairs": 2000,
        "deadline_reserve_frac": 0.12,
        "fold_consistency_gate": True,
        "fold_consistency_min_frac": 0.65,
        "noise_probes": 5,
        "noise_probe_quantile": 0.5,
        "meta_gate": True,
        "meta_gate_epsilon": -0.02,
        "use_op_priors": True,
        "warm_start_battery": True,
        "warm_start_top_k": 8,
        "proxy_max_rows": 5000,
    },
    "best": {
        # Deeper search with controlled patience
        "n_generations": 45,
        "n_parents": 40,
        "n_children": 240,
        "early_stopping_child_eval": 55,
        "early_stopping_iter": 8,
        "min_pct_gain": 0.0015,
        "max_gen_new_feats_pct": 2.0,
        "time_budget": 60 * 60 * 1, # 1 hours
        "cv": 5,
        "ranking_method": "multi_criteria",
        "search_sample_size": 15_000,
        "cache_size_mb": 2000,
        "use_proxy_evaluation": True,
        "proxy_top_pct": 0.12,
        "meta_validation_frac": 0.15,
        "rotate_cv_folds": True,
        "fold_rotation_period": 5,
        # --- search upgrades ---
        "prefilter_candidates": True,
        "near_dup_threshold": 0.99,
        "proxy_fast_mode": True,
        "proxy_num_rounds": 30,
        "proxy_pipeline_candidates": True,
        "elite_ranking": "proxy_blend",
        "cache_baseline_evals": True,
        "importance_refresh_period": 3,
        "shap_refresh_period": 5,
        "shap_interactions_max_pairs": 2000,
        "deadline_reserve_frac": 0.12,
        "fold_consistency_gate": True,
        "fold_consistency_min_frac": 0.65,
        "noise_probes": 5,
        "noise_probe_quantile": 0.5,
        "meta_gate": True,
        "meta_gate_epsilon": -0.02,
        "use_op_priors": True,
        "warm_start_battery": True,
        "warm_start_top_k": 10,
        "proxy_max_rows": 6000,
    },
    "extreme": {
        # Maximum thoroughness with efficiency guardrails
        "n_generations": 80,
        "n_parents": 60,
        "n_children": 360,
        "early_stopping_child_eval": 80,
        "early_stopping_iter": 12,
        "min_pct_gain": 0.0010,
        "max_gen_new_feats_pct": 3.0,
        "time_budget": 60 * 60 * 4, # 4 hours
        "cv": 5,
        "ranking_method": "multi_criteria",
        "search_sample_size": 15_000,
        "cache_size_mb": 2000,
        "use_proxy_evaluation": True,
        "proxy_top_pct": 0.10,
        "meta_validation_frac": 0.15,
        "rotate_cv_folds": True,
        "fold_rotation_period": 5,
        # --- search upgrades ---
        "prefilter_candidates": True,
        "near_dup_threshold": 0.99,
        "proxy_fast_mode": True,
        "proxy_num_rounds": 30,
        "proxy_pipeline_candidates": True,
        "elite_ranking": "proxy_blend",
        "cache_baseline_evals": True,
        "importance_refresh_period": 3,
        "shap_refresh_period": 5,
        "shap_interactions_max_pairs": 2000,
        "deadline_reserve_frac": 0.12,
        "fold_consistency_gate": True,
        "fold_consistency_min_frac": 0.65,
        "noise_probes": 5,
        "noise_probe_quantile": 0.5,
        "meta_gate": True,
        "meta_gate_epsilon": -0.02,
        "use_op_priors": True,
        "warm_start_battery": True,
        "warm_start_top_k": 10,
        "proxy_max_rows": 8000,
    }
}
